### ISSUE TITLE
z3 able to solve missing numbers?

### ISSUE THREAD

**Issue by RBRV1** [d0nutptr/v8_rand_buster#1] opened 2023-03-08 13:58 UTC
Hi,

I loved the Youtube video - you explained it very well and it was all very interesting. Tried out the python script also and works great.

I was curious how "bust-able" do you think the states would be if we were to be missing between maybe 0-5 calls to Math.random() inbetween each submitted observed ints.

So for example imagine we had these ints:
176839  [available]
27228   [missing]
240473 [missing] 
334066 [missing]
368492  [available]
202952  [missing]
292661 [missing]
57048  [available]
295167  [available]
128978 [missing]
187419 [available]
199066 [available]

And of course we'd be loading only the [available] ones into the script so whilst they are in order still we'd be missing a few calls here and there. Would Z3 be able to handle a case like that or does it only like it when you have every input in order?

I'd love to hear your thoughts :) Cheers

**Comment by d0nutptr** [comment] 2023-03-09 09:59
Hello!

I've actually done this before! If you have a good sense for _which_ random calls were missed, Z3 is still able to figure out the seed. It can take a fair bit more time and possibly more data in those instances though!

But yea, I can confirm that this does work in practice :) (Though I was doing this with every other value, not with larger gaps like 5)

**Comment by RBRV1** [comment] 2023-07-03 09:43
Sorry for only getting back to you, githubs emails went into my junk for some reason. Good to hear that you managed to do it I'll give it a test with larger gaps. When working with google RNG say the range was between 5000-10000 instead of 1 and a number would I just set the multiple as 10000-5000=5000?

-- scratch that; just rewatched your youtube video and realized I could just take 5000 off the inputs and re-add it to the outputs at the end and it works. thanks

**Comment by d0nutptr** [comment] 2023-10-20 04:29
Sounds good!

Sorry for the delay here. I'll close it since it sounds like you figured it out!

**Closed as completed by d0nutptr** 2023-10-20 04:29 UTC
